from playground.network.message.definitions.playground.base.RegisterGate        import CURRENT_VERSION as RegisterGate
from playground.network.message.definitions.playground.base.UnregisterGate      import CURRENT_VERSION as UnregisterGate
from playground.network.message.definitions.playground.base.GateRegistered      import CURRENT_VERSION as GateRegistered 
from playground.network.message.definitions.playground.base.GateUnregistered    import CURRENT_VERSION as GateUnregistered
from playground.network.message.definitions.playground.base.Gate2GateMessage    import CURRENT_VERSION as Gate2GateMessage
from playground.network.message.definitions.playground.base.Gate2GateReservation import CURRENT_VERSION as Gate2GateReservation
from playground.network.message.definitions.playground.base.Gate2GateResponse   import CURRENT_VERSION as Gate2GateResponse
from RunMobileCode         import CURRENT_VERSION as RunMobileCode
from MobileCodeResult      import CURRENT_VERSION as MobileCodeResult
from GetPeers              import CURRENT_VERSION as GetPeers
from Peers                 import CURRENT_VERSION as Peers 